/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserReview = IDL.Record({
  'associatedItem' : IDL.Text,
  'user' : IDL.Principal,
  'author' : IDL.Principal,
  'comment' : IDL.Text,
  'rating' : IDL.Opt(IDL.Nat),
});
export const Activity = IDL.Record({
  'name' : IDL.Text,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const ItineraryDay = IDL.Record({
  'morning' : IDL.Vec(Activity),
  'evening' : IDL.Vec(Activity),
  'afternoon' : IDL.Vec(Activity),
});
export const ItineraryRequest = IDL.Record({
  'id' : IDL.Text,
  'destination' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'createdBy' : IDL.Principal,
  'travelDates' : IDL.Record({ 'end' : IDL.Text, 'start' : IDL.Text }),
  'budgetTier' : IDL.Text,
});
export const TransportSuggestion = IDL.Record({
  'to' : IDL.Text,
  'from' : IDL.Text,
  'mode' : IDL.Text,
  'costEstimate' : IDL.Text,
  'estimatedTime' : IDL.Text,
});
export const RestaurantSuggestion = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'mealTime' : IDL.Text,
});
export const Itinerary = IDL.Record({
  'id' : IDL.Text,
  'days' : IDL.Vec(ItineraryDay),
  'request' : ItineraryRequest,
  'transport' : IDL.Vec(TransportSuggestion),
  'restaurants' : IDL.Vec(RestaurantSuggestion),
  'sharedLink' : IDL.Opt(IDL.Text),
});
export const TravelGuide = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'exampleItineraries' : IDL.Vec(Itinerary),
  'description' : IDL.Text,
  'season' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmailCapture = IDL.Record({
  'interests' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'requestedDate' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'subscriptionTier' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([UserReview], [], []),
  'addTravelGuide' : IDL.Func([TravelGuide], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'captureEmail' : IDL.Func([EmailCapture], [], []),
  'exportItineraryAsPdf' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], []),
  'generateShareableLink' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmailCaptures' : IDL.Func([], [IDL.Vec(EmailCapture)], ['query']),
  'getItinerariesByDestination' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Itinerary)],
      ['query'],
    ),
  'getItinerary' : IDL.Func([IDL.Text], [IDL.Opt(Itinerary)], ['query']),
  'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(UserReview)], ['query']),
  'getTravelGuides' : IDL.Func([], [IDL.Vec(TravelGuide)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitItineraryRequest' : IDL.Func([ItineraryRequest], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserReview = IDL.Record({
    'associatedItem' : IDL.Text,
    'user' : IDL.Principal,
    'author' : IDL.Principal,
    'comment' : IDL.Text,
    'rating' : IDL.Opt(IDL.Nat),
  });
  const Activity = IDL.Record({
    'name' : IDL.Text,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const ItineraryDay = IDL.Record({
    'morning' : IDL.Vec(Activity),
    'evening' : IDL.Vec(Activity),
    'afternoon' : IDL.Vec(Activity),
  });
  const ItineraryRequest = IDL.Record({
    'id' : IDL.Text,
    'destination' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'createdBy' : IDL.Principal,
    'travelDates' : IDL.Record({ 'end' : IDL.Text, 'start' : IDL.Text }),
    'budgetTier' : IDL.Text,
  });
  const TransportSuggestion = IDL.Record({
    'to' : IDL.Text,
    'from' : IDL.Text,
    'mode' : IDL.Text,
    'costEstimate' : IDL.Text,
    'estimatedTime' : IDL.Text,
  });
  const RestaurantSuggestion = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'mealTime' : IDL.Text,
  });
  const Itinerary = IDL.Record({
    'id' : IDL.Text,
    'days' : IDL.Vec(ItineraryDay),
    'request' : ItineraryRequest,
    'transport' : IDL.Vec(TransportSuggestion),
    'restaurants' : IDL.Vec(RestaurantSuggestion),
    'sharedLink' : IDL.Opt(IDL.Text),
  });
  const TravelGuide = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'exampleItineraries' : IDL.Vec(Itinerary),
    'description' : IDL.Text,
    'season' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmailCapture = IDL.Record({
    'interests' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'requestedDate' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'subscriptionTier' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([UserReview], [], []),
    'addTravelGuide' : IDL.Func([TravelGuide], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'captureEmail' : IDL.Func([EmailCapture], [], []),
    'exportItineraryAsPdf' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], []),
    'generateShareableLink' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmailCaptures' : IDL.Func([], [IDL.Vec(EmailCapture)], ['query']),
    'getItinerariesByDestination' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Itinerary)],
        ['query'],
      ),
    'getItinerary' : IDL.Func([IDL.Text], [IDL.Opt(Itinerary)], ['query']),
    'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(UserReview)], ['query']),
    'getTravelGuides' : IDL.Func([], [IDL.Vec(TravelGuide)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitItineraryRequest' : IDL.Func([ItineraryRequest], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };