/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'name' : string,
  'type' : string,
  'description' : string,
  'location' : string,
}
export interface EmailCapture {
  'interests' : Array<string>,
  'email' : string,
  'requestedDate' : string,
}
export type ExternalBlob = Uint8Array;
export interface Itinerary {
  'id' : string,
  'days' : Array<ItineraryDay>,
  'request' : ItineraryRequest,
  'transport' : Array<TransportSuggestion>,
  'restaurants' : Array<RestaurantSuggestion>,
  'sharedLink' : [] | [string],
}
export interface ItineraryDay {
  'morning' : Array<Activity>,
  'evening' : Array<Activity>,
  'afternoon' : Array<Activity>,
}
export interface ItineraryRequest {
  'id' : string,
  'destination' : string,
  'interests' : Array<string>,
  'createdBy' : Principal,
  'travelDates' : { 'end' : string, 'start' : string },
  'budgetTier' : string,
}
export interface RestaurantSuggestion {
  'name' : string,
  'description' : string,
  'location' : string,
  'mealTime' : string,
}
export interface TransportSuggestion {
  'to' : string,
  'from' : string,
  'mode' : string,
  'costEstimate' : string,
  'estimatedTime' : string,
}
export interface TravelGuide {
  'id' : string,
  'title' : string,
  'exampleItineraries' : Array<Itinerary>,
  'description' : string,
  'season' : [] | [string],
}
export interface UserProfile {
  'name' : string,
  'subscriptionTier' : string,
  'email' : [] | [string],
}
export interface UserReview {
  'associatedItem' : string,
  'user' : Principal,
  'author' : Principal,
  'comment' : string,
  'rating' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[UserReview], undefined>,
  'addTravelGuide' : ActorMethod<[TravelGuide], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'captureEmail' : ActorMethod<[EmailCapture], undefined>,
  'exportItineraryAsPdf' : ActorMethod<[string], [] | [ExternalBlob]>,
  'generateShareableLink' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmailCaptures' : ActorMethod<[], Array<EmailCapture>>,
  'getItinerariesByDestination' : ActorMethod<[string], Array<Itinerary>>,
  'getItinerary' : ActorMethod<[string], [] | [Itinerary]>,
  'getReviews' : ActorMethod<[string], Array<UserReview>>,
  'getTravelGuides' : ActorMethod<[], Array<TravelGuide>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitItineraryRequest' : ActorMethod<[ItineraryRequest], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];